version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: 
      context: .
      dockerfile: NodeDockerfile
    ports:
      - "4000:4000"
    links:
      - mongo
  client:
    build:
      context: .
      dockerfile: VueDockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "80:80"
    depends_on:
      - server
